---
fixtures:
  repositories:
    logrotate: https://github.com/simp/pupmod-simp-logrotate.git
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    stdlib: https://github.com/simp/puppetlabs-stdlib.git
    systemd: https://github.com/simp/puppet-systemd.git
  symlinks:
    sudosh: "#{source_dir}"
